# Generated by Django 4.1 on 2023-12-11 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friend", "0002_remove_friendrequest_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendrequest",
            unique_together={("sender", "receiver")},
        ),
    ]
