# Generated by Django 4.1 on 2023-12-13 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friend", "0003_alter_friendrequest_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendlist",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friend_list", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
