# Generated by Django 4.1 on 2023-12-13 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodOption",
            fields=[
                (
                    "dish",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "cuisine",
                    models.CharField(
                        choices=[
                            ("African", "African"),
                            ("American", "American"),
                            ("Mexican", "Mexican"),
                            ("Peruvian", "Peruvian"),
                            ("Caribean", "Caribean"),
                            ("Other Latinoamerican", "Other Latam"),
                            ("Chinese", "Chinese"),
                            ("Corean", "Corean"),
                            ("Japanese", "Japanese"),
                            ("Thai", "Thai"),
                            ("Other Asian", "Other Asian"),
                            ("Italian", "Italian"),
                            ("Mediterranean", "Mediterranean"),
                            ("Eastern European", "East Eur"),
                            ("Other European", "Other Eur"),
                            ("Oceanic", "Oceanic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("spicy", models.BooleanField()),
                ("gluten_free", models.BooleanField()),
                ("vegetarian", models.BooleanField()),
                ("image", models.ImageField(upload_to="food")),
            ],
            options={
                "verbose_name": "FoodOption",
                "verbose_name_plural": "FoodOptions",
            },
        ),
        migrations.CreateModel(
            name="PreviousFoodDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodoptions.foodoption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FoodDecision",
                "verbose_name_plural": "FoodDecisions",
            },
        ),
        migrations.CreateModel(
            name="CurrentFoodChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked", models.BooleanField()),
                (
                    "chooser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodoptions.foodoption",
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_friend",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CurrentChoice",
                "verbose_name_plural": "CurrentChoices",
                "unique_together": {("chooser", "friend", "dish")},
            },
        ),
    ]
